src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    #[Assert\Regex('/^[a-z0-9.-]*$/')]
    private ?string $username = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $avatar = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $birthday = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    #[Assert\Length(min: 20)]
    private ?string $biography = null;

    #[ORM\OneToMany(mappedBy: 'creator', targetEntity: Post::class, orphanRemoval: true)]
    #[ORM\OrderBy(['createdAt' => 'DESC'])]
    private Collection $posts;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(?\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(?string $biography): self
    {
        $this->biography = $biography;

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setCreator($this);
        }

        return $this;
    }

    public function removePost(Post $post): self
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getCreator() === $this) {
                $post->setCreator(null);
            }
        }

        return $this;
    }

    public function getAge()
    {
        if ($this->birthday) {
            return $this->birthday->diff(new \DateTime())->y;
        }
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Entity\User;
use App\Form\EditProfileType;
use App\Form\PostType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class UserController extends AbstractController
{
    #[Route('/membres', name: 'app_user')]
    #[IsGranted('ROLE_USER')]
    public function index(UserRepository $repository): Response
    {
        return $this->render('user/index.html.twig', [
            'members' => $repository->findAll(),
        ]);
    }

    #[Route('/membre/{username}', name: 'app_user_show')]
    public function show(Request $request, User $user, EntityManagerInterface $manager): Response
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $post->setCreator($this->getUser());

            $manager->persist($post);
            $manager->flush();

            return $this->redirectToRoute('app_user_show', ['username' => $this->getUser()->getUsername()]);
        }

        return $this->render('user/show.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/membre/profil/modifier', name: 'app_user_edit')]
    #[IsGranted('ROLE_USER')]
    public function edit(Request $request, EntityManagerInterface $manager, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(EditProfileType::class, $user = $this->getUser());
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Pseudo => Fio rella => fio-rella
            if (!$user->getUsername()) {
                $user->setUsername($slugger->slug($user->getFirstname())->lower());
            }

            /** @var UploadedFile $file */
            $file = $form->get('avatarFile')->getData();

            if ($file) {
                $publicDir = __DIR__.'/../../public';

                if ($user->getAvatar()) {
                    $filesystem = new Filesystem();
                    $filesystem->remove($publicDir.'/'.$user->getAvatar());
                }

                $file->move($publicDir.'/users', $avatar = $user->getUsername().'-'.uniqid().'.'.$file->guessExtension());
                $user->setAvatar('users/'.$avatar);
            }

            $manager->flush();

            return $this->redirectToRoute('app_user_show', ['username' => $user->getUsername()]);
        }

        return $this->render('user/edit.html.twig', [
            'form' => $form->createView(),
            'user' => $this->getUser(),
        ]);
    }
}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier votre profil - {{ parent() }}{% endblock %}

{% block body %}
    <div class="flex flex-wrap lg:flex-nowrap">
        <div class="lg:w-1/3 lg:mr-10">
            <div class="bg-white rounded-md">
                {% if user.avatar %}
                <img class="w-full rounded-t-md" src="{{ asset(user.avatar) }}" alt="{{ user.firstname }}">
                {% endif %}
                <div class="p-3">
                    <h2 class="text-2xl font-bold">{{ user.firstname }}</h2>
                    {% if user.birthday %}
                    <p class="text-gray-600 border-b pb-2 mb-2">Né(e) le {{ user.birthday.format('d/m/Y') }} ({{ user.age }} ans)</p>
                    {% endif %}
                    <p class="text-sm text-gray-600 border-b pb-2 mb-2">
                        <strong>Email:</strong>
                        {{ user.email }}
                    </p>
                    {% if user.biography %}
                    <div class="text-sm text-gray-600">
                        <strong>Biographie:</strong>
                        <p>{{ user.biography }}</p>
                    </div>
                    {% endif %}
                </div>
            </div>

            {% if app.user == user %}
                <div class="text-center mt-4">
                    <a href="{{ path('app_user_edit') }}" class="inline-block px-6 py-2 bg-blue-500 hover:bg-blue-600 rounded text-white shadow-md duration-300">Modifier</a>
                </div>

                <div class="text-center mt-4">
                    <a href="{{ path('app_logout') }}" class="inline-block px-6 py-2 bg-red-500 hover:bg-red-600 rounded text-white shadow-md duration-300">Déconnexion</a>
                </div>
            {% endif %}
        </div>
        <div class="lg:w-2/3">
            {{ form_start(form) }}
                {{ form_row(form.firstname) }}
                {{ form_row(form.username) }}
                {{ form_row(form.avatarFile) }}
                {{ form_widget(form) }}

                <button class="inline-block px-6 py-2 bg-blue-500 hover:bg-blue-600 rounded text-white shadow-md duration-300" formnovalidate>Modifier</button>
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos membres - {{ parent() }}{% endblock %}

{% block body %}
    <div class="flex flex-wrap">
        {% for user in members %}
            <div class="w-1/2 lg:w-1/5 mb-3">
                <div class="bg-white rounded-t mx-2 border">
                    <a href="{{ path('app_user_show', { username: user.username }) }}">
                        {% if user.avatar %}
                        <img class="w-full h-32 object-cover rounded-t" src="{{ asset(user.avatar) }}" alt="{{ user.firstname }}">
                        {% endif %}
                        <div class="px-2 py-4">
                            <p>
                                <span class="text-blue-500">{{ user.firstname }}</span>
                                {% if user.age %}
                                    ({{ user.age }} ans)
                                {% endif %}
                            </p>
                            <p>{{ user.posts.count }} publications</p>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil de {{ user.firstname }} - {{ parent() }}{% endblock %}

{% block body %}
    <div class="flex flex-wrap lg:flex-nowrap">
        <div class="lg:w-1/3 lg:mr-10">
            <div class="bg-white rounded-md">
                {% if user.avatar %}
                <img class="w-full rounded-t-md" src="{{ asset(user.avatar) }}" alt="{{ user.firstname }}">
                {% endif %}
                <div class="p-3">
                    <h2 class="text-2xl font-bold">{{ user.firstname }}</h2>
                    {% if user.birthday %}
                    <p class="text-gray-600 border-b pb-2 mb-2">Né(e) le {{ user.birthday.format('d/m/Y') }} ({{ user.age }} ans)</p>
                    {% endif %}
                    <p class="text-sm text-gray-600 border-b pb-2 mb-2">
                        <strong>Email:</strong>
                        {{ user.email }}
                    </p>
                    {% if user.biography %}
                    <div class="text-sm text-gray-600">
                        <strong>Biographie:</strong>
                        <p>{{ user.biography }}</p>
                    </div>
                    {% endif %}
                </div>
            </div>

            {% if app.user == user %}
                <div class="text-center mt-4">
                    <a href="{{ path('app_user_edit') }}" class="inline-block px-6 py-2 bg-blue-500 hover:bg-blue-600 rounded text-white shadow-md duration-300">Modifier</a>
                </div>

                <div class="text-center mt-4">
                    <a href="{{ path('app_logout') }}" class="inline-block px-6 py-2 bg-red-500 hover:bg-red-600 rounded text-white shadow-md duration-300">Déconnexion</a>
                </div>
            {% endif %}
        </div>
        <div class="lg:w-2/3">
            {% if app.user == user %}
                {{ form_start(form) }}
                    <div class="flex items-center">
                        <div class="flex-grow">
                            {{ form_widget(form) }}    
                        </div>
                        <div class="ml-4">
                            <button class="inline-block px-6 py-2 bg-blue-500 hover:bg-blue-600 rounded text-white shadow-md duration-300" formnovalidate>Publier</button>
                        </div>
                    </div>
                {{ form_end(form) }}
            {% endif %}

            {% for post in user.posts %}
                {{ include('_post.html.twig') }}
            {% endfor %}
        </div>
    </div>
{% endblock %}